name: Checkins

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: "0 9 * * *"

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: "Set up Python"
        uses: actions/setup-python@v4.7.0

      - name: "Install requirements"
        run: |
          pip3 install -r ./requirements.txt

      - name: Checkin
        run: |
          python3 ./v2free.py ${{ secrets.USER }} ${{ secrets.PWD }}

      - name: Commit
        run: |
          git config --global user.email kysonyangs@gmail.com
          git config --global user.name bots
          git add .
          git commit -m "Update flow.log" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
